<a href="https://colab.research.google.com/github/shubhamgautam1211/Machine-Learning-Standalone/blob/main/SG_5_AlgebraOperations_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Download the Red Wine Dataset from https://archive.ics.uci.edu/ml/machinelearning-databases/wine-quality/winequality-red.csv**


# **STEP-1**

In [ ]:
import csv
with open('winequality-red.csv', 'r') as f:
    XY = list(csv.reader(f, delimiter=';'))

## **STEP-2(Storing the dataset as a 2D numPy Matrix)**

In [ ]:
import numpy as np
XY = np.array(XY[1:], dtype=np.float)
XY

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])

# **STEP-3**

In [ ]:
XY.shape

(1599, 12)

**Flattening the 2d array to a 1d array**

In [ ]:
flat = XY.flatten()   # 2D to 1D
print("1D array is")
print(flat)
print("Shape is")
print(flat.shape)

1D array is
[ 7.4   0.7   0.   ...  0.66 11.    6.  ]
Shape is
(19188,)


**Column Slicing the Numpy Array**

In [ ]:
col_feature = XY[:, :-1]
print(col_feature)
print(col_feature.shape)

col_target = XY[0:,11:]
print(col_target)
print(col_target.shape)

[[ 7.4    0.7    0.    ...  3.51   0.56   9.4  ]
 [ 7.8    0.88   0.    ...  3.2    0.68   9.8  ]
 [ 7.8    0.76   0.04  ...  3.26   0.65   9.8  ]
 ...
 [ 6.3    0.51   0.13  ...  3.42   0.75  11.   ]
 [ 5.9    0.645  0.12  ...  3.57   0.71  10.2  ]
 [ 6.     0.31   0.47  ...  3.39   0.66  11.   ]]
(1599, 11)
[[5.]
 [5.]
 [5.]
 ...
 [6.]
 [5.]
 [6.]]
(1599, 1)


**Row Slicing the Numpy Array**

In [ ]:
Row = np.vsplit(XY,[800,12])
print("USING VSPLIT FUNCTION IN NUMPY")
print(Row)

print("USING SLICING")

sliced_firstequal_XY = XY[0: (len(XY)//2)+1,0:]
sliced_secondequal_XY = XY[(len(XY)//2): ,0:]

print("First Half")
print(sliced_firstequal_XY)
print(sliced_firstequal_XY.shape)
print("Second Half")
print(sliced_secondequal_XY)
print(sliced_secondequal_XY.shape)

USING VSPLIT FUNCTION IN NUMPY
[array([[9.40e+00, 4.30e-01, 2.40e-01, ..., 7.30e-01, 1.00e+01, 6.00e+00],
       [7.20e+00, 3.60e-01, 4.60e-01, ..., 8.50e-01, 1.10e+01, 7.00e+00],
       [9.30e+00, 3.60e-01, 3.90e-01, ..., 7.30e-01, 1.09e+01, 6.00e+00],
       ...,
       [6.80e+00, 5.10e-01, 1.00e-02, ..., 5.60e-01, 9.50e+00, 6.00e+00],
       [9.40e+00, 4.00e-01, 4.70e-01, ..., 5.00e-01, 1.05e+01, 5.00e+00],
       [6.90e+00, 7.65e-01, 1.80e-01, ..., 6.00e-01, 1.03e+01, 6.00e+00]]), array([], shape=(0, 12), dtype=float64), array([[11.9 ,  0.37,  0.69, ...,  0.65, 12.8 ,  6.  ],
       [ 7.3 ,  0.65,  0.  , ...,  0.47, 10.  ,  7.  ],
       [ 7.6 ,  0.55,  0.21, ...,  0.55,  9.7 ,  5.  ],
       ...,
       [ 7.2 ,  0.56,  0.26, ...,  0.52,  9.9 ,  5.  ],
       [ 7.  ,  0.43,  0.3 , ...,  0.46, 11.9 ,  6.  ],
       [ 9.1 ,  0.6 ,  0.  , ...,  0.63, 10.4 ,  6.  ]])]
USING SLICING
First Half
[[9.40e+00 4.30e-01 2.40e-01 ... 7.30e-01 1.00e+01 6.00e+00]
 [7.20e+00 3.60e-01 4.60e-01 ... 

In [ ]:
np.random.shuffle(XY)
print(XY)

[[ 9.4   0.43  0.24 ...  0.73 10.    6.  ]
 [ 7.2   0.36  0.46 ...  0.85 11.    7.  ]
 [ 9.3   0.36  0.39 ...  0.73 10.9   6.  ]
 ...
 [ 7.2   0.56  0.26 ...  0.52  9.9   5.  ]
 [ 7.    0.43  0.3  ...  0.46 11.9   6.  ]
 [ 9.1   0.6   0.   ...  0.63 10.4   6.  ]]


In [ ]:
trans = np.transpose(XY)  #TRANSPOSE
print(trans)

[[ 9.4   7.2   9.3  ...  7.2   7.    9.1 ]
 [ 0.43  0.36  0.36 ...  0.56  0.43  0.6 ]
 [ 0.24  0.46  0.39 ...  0.26  0.3   0.  ]
 ...
 [ 0.73  0.85  0.73 ...  0.52  0.46  0.63]
 [10.   11.   10.9  ...  9.9  11.9  10.4 ]
 [ 6.    7.    6.   ...  5.    6.    6.  ]]


In [ ]:
print(trans.shape)

(12, 1599)


Slicing the first 10 rows and the 10 columns of the matrix for computing Inverse and Determinant

In [ ]:
# SQUARE MATRIX = equal rows and columns
C = XY[0:10,0:10]
C

array([[9.4000e+00, 4.3000e-01, 2.4000e-01, 2.8000e+00, 9.2000e-02,
        1.4000e+01, 4.5000e+01, 9.9800e-01, 3.1900e+00, 7.3000e-01],
       [7.2000e+00, 3.6000e-01, 4.6000e-01, 2.1000e+00, 7.4000e-02,
        2.4000e+01, 4.4000e+01, 9.9534e-01, 3.4000e+00, 8.5000e-01],
       [9.3000e+00, 3.6000e-01, 3.9000e-01, 1.5000e+00, 8.0000e-02,
        4.1000e+01, 5.5000e+01, 9.9652e-01, 3.4700e+00, 7.3000e-01],
       [8.9000e+00, 1.2000e-01, 4.5000e-01, 1.8000e+00, 7.5000e-02,
        1.0000e+01, 2.1000e+01, 9.9552e-01, 3.4100e+00, 7.6000e-01],
       [1.1100e+01, 3.1000e-01, 5.3000e-01, 2.2000e+00, 6.0000e-02,
        3.0000e+00, 1.0000e+01, 9.9572e-01, 3.0200e+00, 8.3000e-01],
       [9.3000e+00, 4.0000e-01, 4.9000e-01, 2.5000e+00, 8.5000e-02,
        3.8000e+01, 1.4200e+02, 9.9780e-01, 3.2200e+00, 5.5000e-01],
       [6.6000e+00, 6.4000e-01, 3.1000e-01, 6.1000e+00, 8.3000e-02,
        7.0000e+00, 4.9000e+01, 9.9718e-01, 3.3500e+00, 6.8000e-01],
       [7.7000e+00, 7.1500e-01, 1.0000e-0

## **INVERSE**

In [ ]:
inverse_array = np.linalg.inv(C)   #INVERSE
inverse_array

array([[-3.45044552e-01, -2.86378900e-01,  4.71281627e-01,
        -3.42301622e-01,  2.88300606e-01, -6.24201630e-01,
        -6.69424239e-02, -1.82783646e-01,  3.40854477e-01,
         7.46928521e-01],
       [-7.59936911e+00,  6.37307163e-01,  8.91226401e-01,
        -6.03322034e+00,  3.24640940e+00, -4.33464776e+00,
        -1.30936027e+00,  1.14630124e+00,  6.85128598e+00,
         6.51787616e+00],
       [-6.22382689e+00,  8.94232385e-02, -2.52921152e-01,
        -1.53707537e+00,  1.88735471e+00,  1.39704742e+00,
         6.74344620e-02,  7.41485823e-01,  3.77132255e+00,
         7.06904696e-02],
       [ 5.82037974e-01, -2.17364180e-01,  2.43260573e-01,
         2.73725780e-01, -1.70815716e-01,  1.86890089e-01,
         3.99908253e-01, -2.37265806e-01, -6.17061405e-01,
        -4.45226560e-01],
       [-1.96661774e+00, -3.04720081e+00, -1.33237558e+00,
        -1.09812832e+01, -7.24627847e+00,  6.30499244e+00,
        -5.00567841e+00,  6.69378915e-02,  2.67723692e+01,
        -3.

In [ ]:
inverse_array.shape

(10, 10)

## **DETERMINANT**

In [ ]:
det = np.linalg.det(C)  #DETERMINANT
det

1.8771140420039982

# **STEP-4**

In [ ]:
with open('winequality-red.csv', 'r') as f:
    XY = list(csv.reader(f, delimiter=';'))
XY = np.array(XY[1:], dtype=np.float)
XY    

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])

In [ ]:
RXY = np.random.randint(1,10,size=(1599,12))
RXY

array([[8, 4, 3, ..., 3, 7, 8],
       [2, 9, 6, ..., 2, 2, 3],
       [3, 1, 6, ..., 4, 8, 7],
       ...,
       [4, 4, 4, ..., 9, 9, 6],
       [1, 2, 2, ..., 3, 5, 5],
       [6, 8, 5, ..., 5, 6, 6]])

In [ ]:
np.add(RXY,XY)  #ADD

array([[15.4  ,  4.7  ,  3.   , ...,  3.56 , 16.4  , 13.   ],
       [ 9.8  ,  9.88 ,  6.   , ...,  2.68 , 11.8  ,  8.   ],
       [10.8  ,  1.76 ,  6.04 , ...,  4.65 , 17.8  , 12.   ],
       ...,
       [10.3  ,  4.51 ,  4.13 , ...,  9.75 , 20.   , 12.   ],
       [ 6.9  ,  2.645,  2.12 , ...,  3.71 , 15.2  , 10.   ],
       [12.   ,  8.31 ,  5.47 , ...,  5.66 , 17.   , 12.   ]])

In [ ]:
np.subtract(XY,RXY) #SUBTRACT

array([[-0.6  , -3.3  , -3.   , ..., -2.44 ,  2.4  , -3.   ],
       [ 5.8  , -8.12 , -6.   , ..., -1.32 ,  7.8  ,  2.   ],
       [ 4.8  , -0.24 , -5.96 , ..., -3.35 ,  1.8  , -2.   ],
       ...,
       [ 2.3  , -3.49 , -3.87 , ..., -8.25 ,  2.   ,  0.   ],
       [ 4.9  , -1.355, -1.88 , ..., -2.29 ,  5.2  ,  0.   ],
       [ 0.   , -7.69 , -4.53 , ..., -4.34 ,  5.   ,  0.   ]])

In [ ]:
np.outer(XY, RXY)  #OUTER PRODUCT = a[i] * b[j]

array([[59.2 , 29.6 , 22.2 , ..., 37.  , 44.4 , 44.4 ],
       [ 5.6 ,  2.8 ,  2.1 , ...,  3.5 ,  4.2 ,  4.2 ],
       [ 0.  ,  0.  ,  0.  , ...,  0.  ,  0.  ,  0.  ],
       ...,
       [ 5.28,  2.64,  1.98, ...,  3.3 ,  3.96,  3.96],
       [88.  , 44.  , 33.  , ..., 55.  , 66.  , 66.  ],
       [48.  , 24.  , 18.  , ..., 30.  , 36.  , 36.  ]])

# **STEP-5**

In [ ]:
RXY2 = np.random.randint(1,10,size=(12,1))
RXY2

array([[9],
       [5],
       [2],
       [7],
       [3],
       [7],
       [2],
       [1],
       [9],
       [4],
       [5],
       [4]])

In [ ]:
XY.dot(RXY2)  #INNER PRODUCT - 1st way 

array([[330.4558 ],
       [503.6108 ],
       [405.393  ],
       ...,
       [472.61374],
       [489.75547],
       [405.03649]])

In [ ]:
inner_product = np.dot(XY,RXY2)  #INNER PRODUCT - 2nd way
inner_product

array([[330.4558 ],
       [503.6108 ],
       [405.393  ],
       ...,
       [472.61374],
       [489.75547],
       [405.03649]])

In [ ]:
inner_product.shape

(1599, 1)

# **STEP-6**

In [ ]:
#The transpose of a matrix is found by switching its rows with its columns
#The determinant of a square matrix can be calculated det() function which also comes from the numpy linalg package
#If the determinant of a square matrix is not 0, it has a true inverse.
#Flatten is a simple method to transform a matrix into a one-dimensional numpy array
#Shuffle can be used to avoid BIAS situations keeping in mind real life applications
#Slicing helps get a particular matrix breakdown into several parts based on conditions, also by use of row or column individualy
#Addition, Subtraction, outer product of Matrix 
#Inner product also called dot produt gives you same output. 